# Numpy

Use numpy because:

- it's compact
- it's fast
- it matches the way we think about math

# Why not just use Python?

![Floating Point](data/img/C-Python-Float.png)

![List](data/img/Python-List-Float.png)

![List](data/img/Numpy-Array.png)

In [2]:
!pip install numpy

    100% |████████████████████████████████| 13.9MB 732kB/s ta 0:00:01
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


# "How fast is it?"

In [3]:
import numpy as np

np.random.seed(0)

def reciprocate(values):
    """Returns an array of 1.0/x for every x in values"""
    result = np.empty(len(values))
    for i, x in enumerate(values):
        result[i] = 1.0 / x
    return result

reciprocate(np.random.randint(1, 10, 10))

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ,
       0.25      , 0.16666667, 0.33333333, 0.2       , 0.125     ])

In [4]:
xs = np.random.randint(1, 10, 1_000_000)

In [5]:
%timeit reciprocate(xs)

2.19 s ± 65 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
%timeit 1.0 / xs

2.62 ms ± 19.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# How compact is it?

In [7]:
!pip install pympler

You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [8]:
from pympler.asizeof import asizeof

In [9]:
asizeof(1)

32

In [10]:
asizeof([])

64

In [11]:
np_array_size = asizeof(xs)
np_array_size

8000096

In [12]:
import random
py_list_size = asizeof([random.randint(256, 10000) for i in range(1_000_000)])

In [13]:
py_list_size

40694296

In [14]:
py_list_size / np_array_size

5.086725959288488

In [15]:
from collections import deque, namedtuple

deck = deque([])
Point = namedtuple('Point', 'x y')

In [16]:
asizeof([])

64

In [17]:
asizeof(())

48

In [18]:
asizeof((1,2))

128

In [19]:
asizeof(Point(1,2))

128

In [20]:
asizeof(deck)

632

In [21]:
asizeof({})

240

In [22]:
asizeof(set())

224

# "Rounding"

In [23]:
x = 1.234
np.trunc(x)

1.0

In [24]:
np.trunc(-x)

-1.0

In [25]:
np.floor(x)

1.0

In [26]:
np.floor(-x)

-2.0

In [27]:
np.ceil(x)

2.0

In [28]:
np.ceil(-x)

-1.0

In [29]:
np.round(x)

1.0

In [30]:
np.round(-x)

-1.0

In [31]:
np.round([1.5, 2.5])

array([2., 2.])

# Creating Numpy arrays

In [32]:
xs = np.array(range(5))
xs, xs.dtype

(array([0, 1, 2, 3, 4]), dtype('int64'))

In [33]:
xs = np.array([1,2,3,4,3.14])
xs, xs.dtype

(array([1.  , 2.  , 3.  , 4.  , 3.14]), dtype('float64'))

In [34]:
xs = np.array(range(5), dtype=float)
xs, xs.dtype

(array([0., 1., 2., 3., 4.]), dtype('float64'))

In [35]:
xs = np.array(range(5), dtype=np.int8)
xs, xs.dtype

(array([0, 1, 2, 3, 4], dtype=int8), dtype('int8'))

In [36]:
xs = np.array([0, 0, 1, 1], dtype=np.int0)
xs, xs.dtype

(array([0, 0, 1, 1]), dtype('int64'))

In [37]:
%timeit np.empty(1_000_000)

147 µs ± 6.36 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [38]:
%timeit np.zeros(1_000_000)

1.02 ms ± 7.88 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Multi-dimensional arrays

In [38]:
np.array([
    [1,2,3],
    [4,5,6]
])

array([[1, 2, 3],
       [4, 5, 6]])

Quick array creation convenience methods

In [39]:
np.zeros(20, dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int8)

In [40]:
np.ones((3, 4), dtype=np.float128)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float128)

In [41]:
np.ones((3, 4, 5), dtype=np.float128)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float128)

In [42]:
xs = np.full((3,4), np.pi)
xs

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [43]:
xs.shape

(3, 4)

# Creating ranges of array values

In [44]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [46]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [48]:
np.arange(10, 50, 5.5)

array([10. , 15.5, 21. , 26.5, 32. , 37.5, 43. , 48.5])

In [49]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [50]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# The `r_` and `c_` helpers

In [39]:
np.r_[:5]

array([0, 1, 2, 3, 4])

In [40]:
np.r_[:5, 200, :5]

array([  0,   1,   2,   3,   4, 200,   0,   1,   2,   3,   4])

In [41]:
np.r_[[1,2,3], [10, 11], 5:1:-0.3]

array([ 1. ,  2. ,  3. , 10. , 11. ,  5. ,  4.7,  4.4,  4.1,  3.8,  3.5,
        3.2,  2.9,  2.6,  2.3,  2. ,  1.7,  1.4,  1.1])

In [42]:
np.r_[0:10:3]

array([0, 3, 6, 9])

In [43]:
np.r_[0:10:3j]

array([ 0.,  5., 10.])

In [44]:
(np.r_[0:10:20j] == np.linspace(0, 10, 20)).all()

True

In [45]:
np.r_[0:10:20]

array([0])

In [46]:
np.c_[:10, :100:10j]

array([[  0.        ,   0.        ],
       [  1.        ,  11.11111111],
       [  2.        ,  22.22222222],
       [  3.        ,  33.33333333],
       [  4.        ,  44.44444444],
       [  5.        ,  55.55555556],
       [  6.        ,  66.66666667],
       [  7.        ,  77.77777778],
       [  8.        ,  88.88888889],
       [  9.        , 100.        ]])

Fast generation of random values

In [47]:
np.random.random((4,4))

array([[0.80351516, 0.44480604, 0.66925971, 0.63053011],
       [0.65843811, 0.24503895, 0.27820458, 0.44202878],
       [0.579177  , 0.29078652, 0.3035797 , 0.13168765],
       [0.46878437, 0.85192625, 0.79180773, 0.75873527]])

In [48]:
np.random.normal(10, 2, (3,3))

array([[11.22273148, 10.2920636 ,  9.79183757],
       [10.70956785, 12.26631001, 11.04919632],
       [ 8.59264221,  7.60657508,  9.39315149]])

In [49]:
np.random.randn(10)

array([-2.24767417,  0.36273125, -1.69640798,  1.3107156 , -0.81141234,
        0.03317467, -0.3370064 ,  0.38684747,  0.014802  ,  0.16753439])

In [50]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
x = np.empty((2,4))
x

array([[-2.00000000e+000,  4.33898537e-311,  1.97626258e-323,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000, -2.00000000e+000,
         5.60607450e-309]])

In [52]:
ys = [np.empty((2,4)) for i in range(4)]
for y in ys:
    print(y)

[[-2.00000000e+000  4.33898537e-311  1.97626258e-323  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000 -2.00000000e+000  5.60607450e-309]]
[[-2.00000000e+000 -2.00000000e+000  1.97626258e-323  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000 -4.33898420e-311  5.60607449e-309]]
[[-2.00000000e+000  4.33898420e-311  2.19284123e-314  2.19203840e-314]
 [ 2.19184099e-314  2.19172803e-314  2.20188475e-314  2.19170419e-314]]
[[-2.00000000e+000  2.32035777e+077  2.47032823e-323  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000 -2.00000000e+000  1.73060189e-077]]


# Converting array types

In [53]:
xs = np.r_[:10:20j]
xs

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [54]:
xs.astype(int)

array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
        8,  9, 10])

# Numpy indexing and slicing

In [55]:
xs = np.random.randint(1, 10, (4, 4))
xs

array([[5, 3, 6, 5],
       [3, 5, 7, 9],
       [3, 9, 3, 5],
       [6, 1, 2, 6]])

In [56]:
xs[1, 1]

5

In [57]:
xs[1]

array([3, 5, 7, 9])

In [58]:
xs[:,1]

array([3, 5, 9, 1])

In [59]:
xs[1:3,1:3]

array([[5, 7],
       [9, 3]])

In [60]:
xs[[1,2], 2]

array([7, 3])

Lists for all indexes work a little different

In [61]:
xs[[1,2], [3,2]]

array([9, 3])

In [62]:
xs

array([[5, 3, 6, 5],
       [3, 5, 7, 9],
       [3, 9, 3, 5],
       [6, 1, 2, 6]])

In [63]:
xs[1, 3], xs[2, 2]

(9, 3)

In [64]:
xs.reshape(16)

array([5, 3, 6, 5, 3, 5, 7, 9, 3, 9, 3, 5, 6, 1, 2, 6])

In [65]:
xs.ravel()

array([5, 3, 6, 5, 3, 5, 7, 9, 3, 9, 3, 5, 6, 1, 2, 6])

In [66]:
np.r_[:9].reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Sometimes you need to take a 1-D array and make a column vector out of it:

In [67]:
xs = np.r_[:10]
xs

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
xs[:, None]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [69]:
xs[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

# Filtering

In [70]:
xs = np.random.randint(0, 5, 10)

In [71]:
xs

array([2, 1, 2, 3, 0, 0, 2, 2, 3, 0])

In [72]:
xs.nonzero()

(array([0, 1, 2, 3, 6, 7, 8]),)

In [73]:
xs[xs.nonzero()]

array([2, 1, 2, 3, 2, 2, 3])

In [74]:
xs < 3

array([ True,  True,  True, False,  True,  True,  True,  True, False,
        True])

In [75]:
xs[xs < 3]

array([2, 1, 2, 0, 0, 2, 2, 0])

In [76]:
xs = np.random.randint(0, 5, (3, 3))
xs

array([[0, 4, 2],
       [1, 3, 0],
       [2, 3, 2]])

In [77]:
xs.nonzero()

(array([0, 0, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 0, 1, 2]))

In [78]:
np.array(xs.nonzero())

array([[0, 0, 1, 1, 2, 2, 2],
       [1, 2, 0, 1, 0, 1, 2]])

In [79]:
xs[xs.nonzero()]

array([4, 2, 1, 3, 2, 3, 2])

Maybe this looks a little cleaner?

In [80]:
np.transpose(xs.nonzero())

array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [2, 0],
       [2, 1],
       [2, 2]])

In [81]:
xs[xs.nonzero()] = 100
xs

array([[  0, 100, 100],
       [100, 100,   0],
       [100, 100, 100]])

# Array views

In [82]:
xs = np.r_[:16].reshape((4,4))
xs

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
xs_view = xs[1:3,1:3]
xs_view

array([[ 5,  6],
       [ 9, 10]])

In [84]:
xs_view[0,0] = 100
xs_view

array([[100,   6],
       [  9,  10]])

In [85]:
xs

array([[  0,   1,   2,   3],
       [  4, 100,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [86]:
xs_view_copy = xs_view.copy()

In [87]:
xs_view_copy[0, 0] = 200
xs_view_copy

array([[200,   6],
       [  9,  10]])

In [88]:
xs

array([[  0,   1,   2,   3],
       [  4, 100,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [89]:
xs_view

array([[100,   6],
       [  9,  10]])

# Numpy universal functions (ufuncs)

Most `np.array` methods also exist as functions in the numpy namespace.

They typically operate well over scalars, numpy arrays, and Python sequences

In [90]:
np.multiply(2, 3)  # scalar / scalar

6

In [91]:
np.multiply(np.r_[:10], 20) # array / scalar

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180])

In [92]:
np.multiply(np.r_[:10], [4] * 10)  # array / list

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [93]:
np.divide(1, 0)

/Users/rick446/.virtualenvs/intermediate-python/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


inf

In [94]:
np.divide([1], [0])

/Users/rick446/.virtualenvs/intermediate-python/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf])

In [95]:
np.divide(1, 0) - np.divide(1, 0)

/Users/rick446/.virtualenvs/intermediate-python/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/rick446/.virtualenvs/intermediate-python/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in double_scalars
  """Entry point for launching an IPython kernel.


nan

In [96]:
1 / np.zeros(10)

/Users/rick446/.virtualenvs/intermediate-python/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [97]:
2 ** np.r_[:9].reshape((3,3))

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

https://docs.scipy.org/doc/numpy/reference/ufuncs.html for the full list of ufuncs

Generally, operators delegate to ufuncs if at least one side of the operation is a numpy type.

# Aggregation

We can apply ufuncs as reduction operators:

In [98]:
xs

array([[  0,   1,   2,   3],
       [  4, 100,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [99]:
np.add.reduce(xs)

array([ 24, 123,  32,  36])

In [100]:
np.add.reduce(xs, axis=1)

array([  6, 117,  38,  54])

In [101]:
np.multiply.reduce(xs)

array([    0, 11700,  1680,  3465])

In [102]:
np.multiply.reduce(xs, axis=1)

array([    0, 16800,  7920, 32760])

In [103]:
np.mean(xs)

13.4375

In [104]:
np.mean(xs, axis=0)

array([ 6.  , 30.75,  8.  ,  9.  ])

In [105]:
np.mean(xs, axis=1)

array([ 1.5 , 29.25,  9.5 , 13.5 ])

# Build your own ufunc

Although this does _not_ give you "compiled C" performance, you can get the casting rules for your own functions using `np.vectorize`

In [106]:
def saturating_adder(maxval):
    def add(x, y):
        return min([x+y, maxval])
    return np.vectorize(add)
    

In [107]:
myadd = saturating_adder(10)

In [108]:
myadd(2, 9)

array(10)

In [109]:
myadd([2,3,4,5], 6)

array([ 8,  9, 10, 10])

In [110]:
myadd([2,3,4,5], np.r_[5:9])

array([ 7,  9, 10, 10])

# Lab

Open the [Numpy Lab][numpy-lab]

[numpy-lab]: ./numpy-lab.ipynb